#!/bin/bash
################################################################################
##
## Log script for the WRS
##
## Authors:
##	- Felipe Torres González (torresfelipex1<AT>gmail.com)
##  	- Daniel Melgarejo García
##
##
## System requirements: sshpass
##
## GNU Lesser General Public License Usage
## This file may be used under the terms of the GNU Lesser
## General Public License version 2.1 as published by the Free Software
## Foundation and appearing in the file LICENSE.LGPL included in the
## packaging of this file.  Please review the following information to
## ensure the GNU Lesser General Public License version 2.1 requirements
## will be met: http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html.
################################################################################

# Enable verbose message output from the script
VERBOSE_MSG=0

# Remote username (in the WRS is 'root' & pass '')
REMOTE_USER='root'
REMOTE_PASS=''

SSH_OPTIONS="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o LogLevel=error"

# Default timeout
INTERVAL=0

# File where the result of each check will be stored
HEADEREDOUT=0

# WRMON log (save calls to the wrs)
WRMON="x"

# Trap Ctrl-C and call ctrl_c() to end the test
trap ctrl_c INT

# Remote device (right now only WRS)
REMOTE_NAME="WRS"
REMOTE_ADDR=

# Enable oven Switchoff
#   This variable allows to connect a relay to the Host to switchoff the
#   equipment if the maximum temperature is reached.
OVENSWITCH="OFF"
GPIOVEN=17

# Enable synchronization checking
SYNC="OFF"

# Temerature control ----

# ENABLE TEMP LOG
TEMP="OFF"

# ENABLE TEMP LOG FOR SFP
SFP_PORT=0

# BUS used for external sensors
BUS="w1"
BUS_PATH=/sys/bus/$BUS/devices/
# DS18B20+ OneWire sensors have an unique address starting by 28
SENSOR_HADDR="28"
SENSORS=0

# Alias to ease the access to the WRS
wrs_cmd()
{
  sshpass -p '' ssh $SSH_OPTIONS root@$REMOTE_ADDR $1 2>&1
}

# -------------------------------------------

# Function to check if a device is alive
check_alive()
{
    if [ $VERBOSE_MSG != 0 ]; then
        echo -e "\033[1mChecking connection with $REMOTE_NAME ($REMOTE_ADDR)...\033[0m"
    fi
    ping -c 1 $1 &> /dev/null
    if [ $? -ne 0 ]; then
      echo -e "\e[31mCould not connect with $REMOTE_NAME($REMOTE_ADDR)\033[0m"
      exit 1
    fi
}

# -------------------------------------------

# Function to scan a bus and search for valid temperature sensors
search_tsensors()
{
    sensors=$(ls $BUS_PATH)
    for entry in $sensors
    do
        haddr=$(echo $entry | cut -d'-' -f1)
        if [ $haddr == $SENSOR_HADDR ]
        then
            if [ $VERBOSE_MSG -eq 1 ]; then
                echo "Temperature sensor detected: $entry"
            fi
            SENSORS_ARRAY[$SENSORS]=$entry
            SENSORS=$(($SENSORS+1))
        fi
    done
}

# -------------------------------------------

# Function to read temperature sensors
read_tsensors()
{
    for s in ${SENSORS_ARRAY[@]}
    do
        temp=$(cat $BUS_PATH/$s/w1_slave)
        temp=$(echo $temp | grep -oh "t=[0-9]\{5\}" | cut -d'=' -f2)
        temp=$(echo "scale=3;$temp/1000" | bc)
        echo -e "$s:$temp \c"
    done
}

# -------------------------------------------

# Function to check the WRS's sw version
# If version is not supported the script exits

wrs_version()
{
    ver=$(wrs_cmd "/wr/bin/wrs_version -v -v")
    ver=$(echo $ver | grep -oh "v[0-9]\.[0-9]*")
    if [ $ver != "v5.0" ];then
        echo "WRS version $ver is not supported."
        exit 1
    fi
}

# -------------------------------------------

# Function to get temperature from external sensors (1W) and
# from the FPGA & PLL of the WRS (wr_mon)
temp_check()
{
    if [[ $VERBOSE_MSG -eq 1 ]]; then
        echo -e "Checking temperatures..."
    fi
    search_tsensors
    cur_temp=$(read_tsensors)
    if [ "$WRMON" == "x" ]; then
        WRMON=$(wrs_cmd "/wr/bin/wr_mon -wt")
    fi
    wrs_temp=$(echo $WRMON | grep -oh "FPGA.* PLL: [0-9]*.[0-9]*")
    #wrs_temp=$(echo -e "${wrs_temp}" | tr -d '[:space:]')
    echo "$cur_temp$wrs_temp"
}

# -------------------------------------------

temp_range_check()
{
	wrs_temps=$1
	if [[ $SENSOR_TAG == "FPGA" ]]; then
		temp_sensor=$(echo $wrs_temps | grep -oh "$SENSOR_TAG: [0-9.]\{4\}." | cut -d' ' -f2)
		temp_sensor=${temp_sensor%.*}

	elif [[ $SENSOR_TAG == "PLL" ]]; then
		temp_sensor=$(echo $wrs_temps | grep -oh "$SENSOR_TAG: [0-9.]\{4\}." | cut -d' ' -f2)
		temp_sensor=${temp_sensor%.*}

	else
		temp_sensor=$(echo $wrs_temps | grep -oh "$SENSOR_TAG:[0-9.]\{4\}." | cut -d':' -f2)
		temp_sensor=${temp_sensor%.*}
	fi

	if [ $OVENSWITCH == "ON" ]; then
	    if [[ $temp_sensor -gt $MAX || $temp_sensor -lt $MIN ]]; then
                echo -e "\nTemperature exceeded ($temp_sensorºC)"
			    echo "Turning off..."
			    python gpio.py $GPIOVEN off
			    exit 1
	    fi
    fi
}

# -------------------------------------------

check_secureoff()
{

if [[ $1 == "" ]]; then
        echo -e "\e[31m-x parameter needs a temperature sensor's name (Sensor_Tag)\033[0m"
        exit 1
    fi
}

#--------------------------------------------

# Check the arguments to sync flag
check_synclevel()
{
    if [[ $1 -ne 1 && $1 -ne 2 ]]; then
        echo -e "\e[31mNot a valid sync level introduced. Exiting...\033[0m"
        exit 1
    fi
}

# -------------------------------------------

wrmonstat()
{
    echo $(wrs_cmd "/wr/bin/wr_mon -we")
}

# -------------------------------------------

# Check the synchronization status of the WRS
sync_check()
{
    if [[ $VERBOSE_MSG -eq 1 ]]; then
        echo -e "Checking synchronization..."
    fi
    WRMON=$1
    if [[ $VERBOSE_MSG -eq 1 ]]; then
        echo -e "\tLink Status: $link_status"
    fi
    # Save linkup and servo state
    wrs_servo=$(echo $WRMON | grep -oh "lock:[0-1]")
    wrs_TF=$(echo $WRMON | grep -oh "ss:.[A-Z_]\{11\}." | cut -d':' -f2)
    echo -e "$wrs_servo sync:$wrs_TF\c"
    if [[ $SYNC_LEVEL -ge 2 ]]; then
      # Save Round Trip Time
      rtt=$(echo $WRMON | grep -oh "mu:[0-9]*" | cut -d':' -f2)
      # Save bitslide values
      drxm=$(echo $WRMON | grep -oh "drxm:[0-9]*" | cut -d':' -f2)
      drxs=$(echo $WRMON | grep -oh "drxs:[0-9]*" | cut -d':' -f2)
      echo -e " rtt:$rtt drxm:$drxm drxs:$drxs"
    fi


}

# -------------------------------------------
check_sfp_temp()
{
    check_sfp=$(echo $(wrs_cmd "/wr/bin/wrs_sfp_temp_lite -p $SFP_PORT"))
    sfp_result=$(echo $check_sfp | cut -d':' -f3)
    echo -e "sfp_temp:$sfp_result"

}

# -------------------------------------------

# -------------------------------------------

# Trap for the ctrl-c key combination
ctrl_c() 
{
    # Called from ctrl-c
    echo -e "\033[1mBye!\033[0m"
    exit 0
}

# -------------------------------------------

# Check that all needed software is installed
# else exit.
check_sw()
{
    command -v bc >/dev/null 2>&1 || { echo >&2 "bc not installed. Will now exit."; exit 1; }
    command -v sshpass >/dev/null 2>&1 || { echo >&2 "sshpass not installed. Will now exit."; exit 1; }
}

help()
{
cat << EOF
Usage: $(basename $0) [options]

Options:
-h|--help           Prints this help
-v|--verbose        Enables verbose mode
-r|--remote         Remote address (IP)
-i|--interval       Checking rate
-d|--header         Write a description header of the log values
-s|--sync           Enable synchronization checking
                    Levels:
                        1 -> Servo state
                        2 -> 1 + RTT and Bitslides
-t|--temp min,max   Enable temperature checking
-e|--sfp port       Log SFP temperature in port
-x|--secureoff      Switchoff oven when temp max is reached.
                    User must specify the lower address of the temp sensor

EOF
exit 0
}

# -------------------------------------------

# Main test loop
test()
{
    # First check that the device is still alive
    check_alive $REMOTE_ADDR
	WRMON=$(wrmonstat)
    # Get temperature values from the sensors
    temps=$(temp_check "$WRMON")

    # Save synchronization status
    if [ $SYNC == "ON" ]; then
        syncs=$(sync_check "$WRMON")
    fi

    # Control of the temperature range
    if [ $TEMP == "ON" ]; then
        temp_range_check "$temps"
        if [[ $? -gt 0 ]]; then exit $?; fi
    fi

    # Get temperature from SFPs
    if [ "$SFP_PORT" -gt 0 ]; then
        sfp_temp=$(check_sfp_temp "$SFP_PORT")
    fi
    echo -e "$(date +%s) $temps $sfp_temp $syncs"
}

# -------------------------------------------

if [ $# -eq 0 ]; then help; exit 1; fi
while [ $# -gt 0 ]; do # Until you run out of parameters . . .
    case "$1" in
        -h|--help) help;;
        -v|--verbose) VERBOSE="-v";;
        -r|--remote) REMOTE_ADDR=$2;shift;;
        -i|--interval) INTERVAL=$2;shift;;
        -d|--header) HEADEREDOUT=1;shift;;
        -t|--temp)
          TEMP="ON";
          MIN=$(echo $2 | cut -d"," -f1);
          MAX=$(echo $2 | cut -d"," -f2);
          shift;;
        -s|--sync)
            SYNC="ON";
            SYNC_LEVEL=$2;
            check_synclevel $SYNC_LEVEL;
            shift;;
        -x|--secureoff)
            OVENSWITCH="ON";
            SENSOR_TAG=$2;
	    check_secureoff $SENSOR_TAG;
            shift;;
        -e|--sfp)
            SFP_PORT=$2;
            shift;;
        *) echo "Unknown arg: $1"; help;;
    esac
    shift   # Check next set of parameters.
done

# Main script -------------------------------

echo -e "\033[1mRunning test...\033[0m"
echo -e "\tConnecting to WRS ($REMOTE_ADDR)"
if [ $HEADEREDOUT == 1 ]; then
    echo "# Epoch seconds $tempsensors $devtemp $synclabels"
fi

check_sw

while true
do
    test
    sleep $INTERVAL
done
